version: "3.8"
networks:
  kafka-net:
    name: kafka-net
    ipam:
      config:
        - subnet: 192.18.0.0/16
        
services:
  kafka1:
    container_name: kafka1
    build: 
      context: config/.
      dockerfile: Dockerfile
    ports:
        - "9092:9092"
    networks:
      kafka-net:
        ipv4_address: 192.18.0.11
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/

  kafka2:
    container_name: kafka2
    build: 
      context: config/.
      dockerfile: Dockerfile
    ports:
        - "9292:9092"
    networks:
      kafka-net:
        ipv4_address: 192.18.0.12
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/

  kafka3:
    container_name: kafka3
    build: 
      context: config/.
      dockerfile: Dockerfile
    ports:
        - "9392:9092"
    networks:
      kafka-net:
        ipv4_address: 192.18.0.13
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/





